<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace MultiFlexi\Ui;

/**
 * Class CredentialTypeForm.
 *
 * Handles the form for editing CredentialType.
 *
 * @no-named-arguments
 */
class CredentialTypeForm extends SecureForm
{
    public \MultiFlexi\CredentialType $credType;

    public function __construct(\MultiFlexi\CredentialType $credtype, array $formProperties = [])
    {
        $this->credType = $credtype;
        $credTypeRow1 = new \Ease\TWB5\Row();
        $companyId = $credtype->getDataValue('company_id');
        $companer = new \MultiFlexi\Company($companyId);

        $logos['helper'] = new CredentialTypeLogo($credtype, ['style' => 'height: 200px'], ['class' => 'img-fluid']);

        if ($companyId) {
            $logos['company'] = new CompanyLogo($companer, ['class' => 'img-fluid']);
        }

        $credTypeRow1->addColumn(2, $logos);
        $credTypeRow1->addColumn(4, [
            new \Ease\TWB5\FormGroup(_('Credential type Name'), new \Ease\Html\InputTextTag('name', empty($credtype->name()) ? ($credtype->getPrototype() ? $credtype->getPrototype()->name() : '').' '.$companer->getRecordName() : $credtype->name())),
            new \Ease\TWB5\FormGroup(_('Owned by Company'), new CompanySelect('company_id', $companyId)),
            new \Ease\TWB5\FormGroup(_('Credential type UUID'), new \Ease\Html\InputTextTag('uuid', $credtype->uuid(), ['disabled'], _('Autogenerated'))),
        ]);
        $helperCol = $credTypeRow1->addColumn(6, new \Ease\TWB5\FormGroup(_('Credential Prototype'), new CredentialPrototypeSelect('prototype', [], (string) $credtype->getDataValue('prototype'))));

        if ($credtype->getDataValue('prototype')) {
            if ($credtype->getPrototype()) {
                $credtype->getPrototype()->prepareConfigForm();

                $helperCol->addItem(new FieldsForm($credtype->getPrototype()->fieldsInternal(), $credtype->getDataValue('prototype')));
            }

            $provided = new \Ease\TWB5\Panel(new \Ease\Html\H4Tag(_('Fields provided')));

            $assigned = $credtype->getFields();

            if ($credtype->getPrototype()) {
                foreach ($credtype->getPrototype()->fieldsProvided() as $fieldProvided) {
                    $fieldRow = new \Ease\TWB5\Row(null, ['style' => 'padding: 5px']);

                    $fieldRow->addColumn(4, $fieldProvided->getCode().'<br><small>'.($fieldProvided->isRequired() ? _('Required') : _('Optional')).' '.$fieldProvided->getType().'</small>');
                    $fieldRow->addColumn(6, $fieldProvided->getName().'<br>'.$fieldProvided->getDescription());

                    $flags = new \Ease\Html\SpanTag();

                    if (\is_object($assigned->getFieldByCode($fieldProvided->getCode()))) {
                        $flags->addItem(new \Ease\TWB5\LinkButton('#', '➕', 'disabled', ['title' => _('Already assigned')]));
                    } else {
                        if ($fieldProvided->isRequired()) {
                            $credtype->addStatusMessage(sprintf(_('The %s field is required for %s'), $fieldProvided->getCode(), $credtype->getPrototype()->name()), 'warning');
                        }

                        $flags->addItem(new \Ease\TWB5\LinkButton('?id='.$credtype->getMyKey().'&addField='.$fieldProvided->getCode(), '➕', 'success', ['title' => _('Add Field to ')]));
                    }

                    $fieldRow->addColumn(2, $flags);

                    $provided->addItem($fieldRow);
                }
            }

            $helperCol->addItem($provided);
        }

        $formContents[] = $credTypeRow1;

        $formContents[] = new \Ease\Html\DivTag($this->credTypeField('new', new \MultiFlexi\ConfigFieldWithHelper('', 'string', '', '')), ['class' => 'border border-primary rounded']);

        $fields = $credtype->getFields(); // Helper?!

        foreach ($fields as $crTypeField) {
            $formContents[] = $this->credTypeField((string) $crTypeField->getMykey() ?? 'new', $crTypeField);
        }

        parent::__construct(['action' => 'credentialtype.php', 'method' => 'POST'], $formContents);
        // $this->setTagProperty('enctype', 'multipart/form-data');

        $submitRow = new \Ease\TWB5\Row();

        if (null === $credtype->getMyKey()) {
            $submitRow->addColumn(2, new \Ease\TWB5\LinkButton('#', '🚀 '._('Test'), 'disabled btn-lg btn-block'));
        } else {
            $submitRow->addColumn(2, new \Ease\TWB5\LinkButton('credentialtype.php?id='.$credtype->getMyKey().'&test=true', '🚀 '._('Test'), 'success btn-lg btn-block'));
        }

        $submitRow->addColumn(8, new \Ease\TWB5\SubmitButton('🍏 '._('Apply'), 'primary btn-lg btn-block', ['title' => _('Apply changes'), 'id' => 'CredentialTypeFormapplybutton']));

        if (null === $credtype->getMyKey()) {
            $submitRow->addColumn(2, new \Ease\TWB5\SubmitButton('⚰️ '._('Remove').' !', 'disabled btn-lg btn-block', ['disabled' => 'true']));
        } else {
            $this->addItem(new \Ease\Html\InputHiddenTag('id', $credtype->getMyKey()));

            if (WebPage::getRequestValue('remove') === 'true') {
                $submitRow->addColumn(2, new \Ease\TWB5\LinkButton('credentialtype.php?delete='.$credtype->getMyKey(), '⚰️ '._('Remove').' !', 'danger btn-lg btn-block'));
            } else {
                $submitRow->addColumn(2, new \Ease\TWB5\LinkButton('credentialtype.php?id='.$credtype->getMyKey().'&remove=true', '⚰️ '._('Remove').' ?', 'warning btn-lg btn-block'));
            }
        }

        $this->addItem(new \Ease\Html\InputHiddenTag('version', (int) $credtype->getDataValue('version')));

        $this->addItem($submitRow);
    }

    public function afterAdd(): void
    {
    }

    private function credTypeField(string $credTypeId, \MultiFlexi\ConfigFieldWithHelper $field): \Ease\TWB5\Row
    {
        $credTypeFieldRow = new \Ease\TWB5\Row();

        $credTypeFieldRow->addColumn(2, new \Ease\TWB5\FormGroup(_('Field Name'), new \Ease\Html\InputTextTag($credTypeId.'[keyname]', $field->getCode())));

        if ($field->isManual()) {
            $credTypeFieldRow->addColumn(2, new \Ease\TWB5\FormGroup(_('Field Type'), new CfgFieldTypeSelect($credTypeId.'[type]', $field->getType())));
            $credTypeFieldRow->addColumn(2, new \Ease\TWB5\FormGroup(_('Field Hint'), new \Ease\Html\InputTextTag($credTypeId.'[hint]', $field->getHint())));
            $credTypeFieldRow->addColumn(2, new \Ease\TWB5\FormGroup(_('Field Default Value'), new \Ease\Html\InputTextTag($credTypeId.'[defval]', $field->getDefaultValue())));
        }

        $helper = $this->credType->getPrototype();

        if ($helper) {
            $credTypeFieldRow->addColumn(2, new \Ease\TWB5\FormGroup(_('Helper Class field'), $helper->providedFieldsSelect($credTypeId.'[helper]', $field->getCode())));
        } else {
            $credTypeFieldRow->addColumn(2, _('No Helper Class chosen yet'));
        }

        if (is_numeric($credTypeId)) {
            $credTypeFieldRow->addColumn(1, new \Ease\TWB5\FormGroup(_('Remove'), new \Ease\Html\ATag('?removefield='.$credTypeId.'&id='.$this->credType->getMyKey(), '❌️')));
        }

        return $credTypeFieldRow;
    }
}
